### ISSUE TITLE
when can you release this project?

### ISSUE THREAD

**Issue by jcyhcs** [nanmi/yolact-trt#1]
hi,professor:
when can you release this project? I'm too impatient to wait to see it.
oh,PLEASE HELP!

**Comment by zzz3bbb3** [comment]
I had release this repo, please commit your problem when you use this code.TKX

**Comment by zhuimeng2080** [comment]
请教大佬，reference: https://medium.com/@nanmi/%E5%A6%82%E4%BD%95%E7%94%A8tensorrt%E9%83%A8%E7%BD%B2yolact-3690e0708a85

这个网址打不开。

**Comment by zzz3bbb3** [comment]
> 请教大佬，参考：[https ://medium.com/@nanmi/%E5%A6%82%E4%BD%95%E7%94%A8tensorrt%E9%83%A8%E7%BD%B2yolact-3690e0708a85](https://medium.com/@nanmi/%E5%A6%82%E4%BD%95%E7%94%A8tensorrt%E9%83%A8%E7%BD%B2yolact-3690e0708a85)
> 
> 这个网址打不开。

可以fanqiang,也可以参考我另一篇<https://zhuanlan.zhihu.com/p/510843962>

**Comment by zhuimeng2080** [comment]
非常感谢大佬的回信。


    用tensorrt 加速推理的时间少了，但是后处理的花费的时间，如果一帧图片中有500个以上的目标的话，就很快降低处理的速度，大概一秒几帧左右。假设对于实时处理的场合，要一秒处理50帧的话，就很难满足实时性了。
















在 2022-05-23 11:12:41，"nanmi" ***@***.***> 写道：

Closed #1 as completed.
